# Generated by Django 5.1.15 on 2026-01-12 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('price_npr', models.PositiveIntegerField(default=0, help_text='Price per user per month in NPR')),
                ('is_active', models.BooleanField(default=True, help_text='Can this plan be assigned to new tenants?')),
                ('max_users', models.PositiveIntegerField(help_text='Maximum number of users allowed')),
                ('max_lead_forms', models.PositiveIntegerField(blank=True, help_text='Maximum lead forms (null = unlimited)', null=True)),
                ('storage_gb_per_user', models.PositiveIntegerField(help_text='Storage per user in GB')),
                ('bulk_email_limit', models.PositiveIntegerField(blank=True, help_text='Monthly bulk email limit (null = unlimited)', null=True)),
                ('bulk_sms', models.BooleanField(default=False, help_text='Is bulk SMS enabled?')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price_npr'],
                'indexes': [models.Index(fields=['is_active'], name='subscriptio_is_acti_dd0689_idx'), models.Index(fields=['code'], name='subscriptio_code_d07513_idx')],
            },
        ),
    ]
